=== DerAlpman/-dotnetopro-coding-dojo---How-large-is-the-resistance/HowLargeIsTheResistance/HowLargeIsTheResistance/Schemas/color_codes_schema.json
{
  "$id": "http://HowLargeIsTheResistance.com/Color_codes_schema.json",
  "$schema": "http://json-schema.org/draft-04/schema",
  "definitions": {},
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "Color",
      "DecimalValue",
      "UnitValue",
      "Multiplier",
      "Tolerance"
    ],
    "properties": {
      "Color": {
        "$id": "#/items/properties/Color",
        "type": "string",
        "title": "The Color Schema",
        "default": "",
        "examples": [
          "keine"
        ],
        "pattern": "^(.*)$"
      },
      "DecimalValue": {
        "$id": "#/items/properties/DecimalValue",
        "type": "string",
        "title": "The Decimal Schema",
        "default": "",
        "examples": [
          "not_allowed"
        ],
        "pattern": "^(.*)$"
      },
      "UnitValue": {
        "$id": "#/items/properties/UnitValue",
        "type": "string",
        "title": "The Unit_position Schema",
        "default": "",
        "examples": [
          "not_allowed"
        ],
        "pattern": "^(.*)$"
      },
      "Multiplier": {
        "$id": "#/items/properties/Multiplier",
        "type": "string",
        "title": "The Multiplier Schema",
        "default": "",
        "examples": [
          "not_allowed"
        ],
        "pattern": "^(.*)$"
      },
      "Tolerance": {
        "$id": "#/items/properties/Tolerance",
        "type": "string",
        "title": "The Tolerance Schema",
        "default": "",
        "examples": [
          "20"
        ],
        "pattern": "^(.*)$"
      }
    }
  },
  "title": "The Root Schema",
  "type": "array"
}

=== DerAlpman/-dotnetopro-coding-dojo---How-large-is-the-resistance/HowLargeIsTheResistance/HowLargeIsTheResistanceTests/TestFiles/color_codes.json
[
  {
    "Color": "keine",
    "DecimalValue": "not_allowed",
    "UnitValue": "not_allowed",
    "Multiplier": "not_allowed",
    "Tolerance": "20"
  },
  {
    "Color": "silber",
    "DecimalValue": "not_allowed",
    "UnitValue": "not_allowed",
    "Multiplier": "-2",
    "Tolerance": "10"
  },
  {
    "Color": "gold",
    "DecimalValue": "not_allowed",
    "UnitValue": "not_allowed",
    "Multiplier": "-1",
    "Tolerance": "5"
  },
  {
    "Color": "schwarz",
    "DecimalValue": "not_allowed",
    "UnitValue": "0",
    "Multiplier": "-0",
    "Tolerance": "not_allowed"
  },
  {
    "Color": "braun",
    "DecimalValue": "1",
    "UnitValue": "1",
    "Multiplier": "1",
    "Tolerance": "1"
  },
  {
    "Color": "rot",
    "DecimalValue": "2",
    "UnitValue": "2",
    "Multiplier": "2",
    "Tolerance": "2"
  },
  {
    "Color": "orange",
    "DecimalValue": "3",
    "UnitValue": "3",
    "Multiplier": "3",
    "Tolerance": "not_allowed"
  },
  {
    "Color": "gelb",
    "DecimalValue": "4",
    "UnitValue": "4",
    "Multiplier": "4",
    "Tolerance": "not_allowed"
  },
  {
    "Color": "grün",
    "DecimalValue": "5",
    "UnitValue": "5",
    "Multiplier": "5",
    "Tolerance": "0,5"
  },
  {
    "Color": "blau",
    "DecimalValue": "6",
    "UnitValue": "6",
    "Multiplier": "6",
    "Tolerance": "0,25"
  },
  {
    "Color": "violett",
    "DecimalValue": "7",
    "UnitValue": "7",
    "Multiplier": "7",
    "Tolerance": "0,1"
  },
  {
    "Color": "grau",
    "DecimalValue": "8",
    "UnitValue": "8",
    "Multiplier": "8",
    "Tolerance": "0,05"
  },
  {
    "Color": "weiß",
    "DecimalValue": "9",
    "UnitValue": "9",
    "Multiplier": "9",
    "Tolerance": "not_allowed"
  }
]
